language: r

env:
- R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

warnings_are_errors: false

os:
- linux
- osx

r:
- release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - _R_CHECK_LATEX_VIGNETTES=FALSE
    - _R_CHECK_WEAVE_VIGNETTES=FALSE

addons:
  apt:
    packages:
    - libgsl0-dev
    - texlive-latex-extra

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install basictex
  fi

branches:
  only:
  - master

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  - export REL=$(echo $PKGVER | grep -o "\." | grep -c "\.")
  - echo $PKGVER $REL
  - R CMD INSTALL --build FLBEIA_$PKGVER.tar.gz
  - rm FLBEIA_$PKGVER.tar.gz
  - export RELEASE_PKG_FILE=$(ls FLBEIA*gz)
  - echo $RELEASE_PKG_FILE

deploy:
  provider: releases
  api_key:
    secure: ZvBCUEmgrZSlS7mwiu/dA5TQIW90qwZwRC74wxDRTdumWqfY+m/9dYUq7v4GO9ZtGGxA4VDhtdC1z+v1GHucjWF/pgEgFfhSefjFe12KpYqVP+FlnqdODx1uKoDN8FyOoUHMHBGV6KorebtFLICf+ldqqhbB/GFPN85bCgcI4lc=
  file: $RELEASE_PKG_FILE
  skip_cleanup: true
  draft: true
  on:
    repo: flr/FLBEIA
    condition: $REL = "2"
